### PR TITLE
New theme

### PR DESCRIPTION
**Pull request by ashyon**
- Pink highlight color
- Pink Mastodon icon
- Dab cat getting started image

### CODE REVIEW

**Comment by wavebeem** [comment]
My only suggestion is to just resize the cat image rather than modifying the CSS. It seems wasteful to download an image larger than we need, and it'd be a simpler change given that. Otherwise it looks great and I'm excited to try out the new colors.

@ubiquill ?

**Comment by ashyon** [comment]
Resize the cat image rather than modifying the CSS... not following your train here?

**Comment by ashyon** [comment]
Agreed, the image doesn't need to be 1000x600 that was just what I used for my tests. We could also just have it use the SVG version and that would be even cheaper.

**Comment by wavebeem** [comment]
image

image

**Comment by ashyon** [comment]
The contain bit is because the image won't normally fit the column, and I wanted to make sure that it did.

**Comment by wavebeem** [comment]
How much smaller is the SVG version? Also that'd be a great idea. SVGs look crisper on retina displays since they can render at higher resolution.

**Comment by wavebeem** [comment]
RE: contain

Oh, OK. That seems fine then.

**Comment by ashyon** [comment]
17KB vs 66KB for the SVG

**Comment by wavebeem** [comment]
That's awesome. Put in the SVG version then!

**Comment by ashyon** [comment]
Done!

**Comment by ashyon** [comment]
My only complaint about the whole thing is that there's not much contrast between the edges of the image and the background, but it doesn't matter much since the edges aren't really what make the image.

**Comment by wavebeem** [comment]
Oh, we can make it even smaller still! Install SVGO and watch the savings.

```
$ npm install -g svgo
$ svgo app/assets/images/mastodon-getting-started.svg
```

**Comment by ashyon** [comment]
Ah yes, Inkscape adds a lot of extra nonsense to the SVG.

**Comment by wavebeem** [comment]
Yup, Inkscape is pretty amazing at that :D

**Comment by ashyon** [comment]
Alright, optimized SVG. @ubiquill merge?

**Comment by wavebeem** [comment]
8.4kb now... nice!

**Pull request merged**
