### PR TITLE
Make columns fill screen for large displays

### PR DESCRIPTION
**Pull request by ashyon**
gosh hecking darn it do you know how many tries it took for me to get this pull request up? so many tries.

### CODE REVIEW

**Comment by wavebeem** [comment]
Also, if you haven't opened an issue for this upstream, I'd go check that it hasn't already been filed and do that :)

**Comment by ashyon** [comment]
The first bit makes sense yeah. I'll make that change. As for the second part, I tried making it both bigger and smaller and it was actually really nice because it would only get a little bit smaller than normal before collapsing into the mobile view, whereas without it there would be a tiny horizontal scroll and nobody likes that.

**Comment by wavebeem** [comment]
OK, that seems fair about `1 1 auto`. We need another issue upstream to make it not go to mobile view so quickly. That screen is plenty wide enough to use multi-column.

**Comment by ashyon** [comment]
Making the columns `1 1 auto` and the drawer `0 0.4 auto` seemed pretty good to me.

**Comment by wavebeem** [comment]
Did you mean `0.4 0 auto` for the drawer? If it gets any smaller it breaks visually.

**Comment by ashyon** [comment]
I didn't see any visual breakage. Can you give a screenshot of this?

**Comment by wavebeem** [comment]
image

**Comment by ashyon** [comment]
Interesting. In your case it seems that you've only changed the parameters of the drawer and not the columns, whereas in my case changing both works fine.

**Comment by wavebeem** [comment]
Oh, you were doing `1 1 auto` for columns right.

**Comment by wavebeem** [comment]
I would still personally rather scroll than have really really tiny columns in that like 1025-1300 pixel range but /shrug

**Comment by ashyon** [comment]
I'll leave it `1 0 auto` if you like

**Comment by wavebeem** [comment]
`1 1 auto` is fine but rather than `0 0.4 auto` on the drawer i'd say `0 1 auto` and then add a `min-width` to the drawer so it's clear how small it's allowed to get.

**Comment by ashyon** [comment]
Fixes applied. Confirm?

**Comment by wavebeem** [comment]
Approved. @ubiquill merge?

**Comment by ubiquill** [comment]
will, merge and update this when not at work! thanks everyone :)

**Pull request merged**
