### PR TITLE
Ui tweaks

### PR DESCRIPTION
**Pull request by ashyon**
Mostly accessibility tweaks. New style for embedded toots, and visibility improvements for most everything else.

### CODE REVIEW

**Comment by lynnco** [comment]
this really makes me want a visual diff, or heroku review apps

in light of having neither thing, can you give me sceenshot diffs of the relevant elements?

**Comment by ashyon** [comment]
You can see a diff in the "files changed" tab :)

**Comment by wavebeem** [comment]
https://github.com/tootsuite/mastodon/issues/317#issuecomment-293719445

This contains the visual before and after yeah?^

**Comment by lynnco** [comment]
^ ah yea, thats what I was asking for

**Comment by ashyon** [comment]
Ah that's what you wanted. Never mind about my comment :P

**Comment by wavebeem** [comment]
I can pull this and deploy tonight but I need a little more time.

**Comment by ashyon** [comment]
Alright. Just added a commit to make the alt-text for the status avatar "avatar" and not a blank string

**Comment by wavebeem** [comment]
Does anybody else wanna second this? I'd be cool to merge and deploy but don't wanna overstep my role here, much less accidentally take down production with nobody to help me if I ruin it lol.

**Comment by wavebeem** [comment]
I tried out the update locally and it all looks legit.

**Pull request merged**
